### ISSUE TITLE
Poetry 1.5.0 removes category field.

### ISSUE THREAD

**Issue by real-yfprojects** [floatingpurr/sync_with_poetry#26]
With v1.5.0 poetry no longer writes a `category` field to `poetry.lock`.
This results in the following error:

```pytb
Traceback (most recent call last):
  File "/home/user/.cache/pre-commit/repo6cjh4d2_/py_env-python3.8/bin/swp", line 8, in <module>
    sys.exit(main())
  File "/home/user/.cache/pre-commit/repo6cjh4d2_/py_env-python3.8/lib/python3.8/site-packages/sync_with_poetry/swp.py", line 170, in main
    retv |= sync_repos(filename, args.all, args.skip, args.config, mapping)
  File "/home/user/.cache/pre-commit/repo6cjh4d2_/py_env-python3.8/lib/python3.8/site-packages/sync_with_poetry/swp.py", line 99, in sync_repos
    poetry_items = PoetryItems(content["package"], all, skip, db)
  File "/home/user/.cache/pre-commit/repo6cjh4d2_/py_env-python3.8/lib/python3.8/site-packages/sync_with_poetry/swp.py", line 58, in __init__
    if ((not all) and package["category"] != "dev") or package["name"] in skip:
  File "/home/user/.cache/pre-commit/repo6cjh4d2_/py_env-python3.8/lib/python3.8/site-packages/tomlkit/items.py", line 1007, in __getitem__
    return self._value[key]
  File "/home/user/.cache/pre-commit/repo6cjh4d2_/py_env-python3.8/lib/python3.8/site-packages/tomlkit/container.py", line 553, in __getitem__
    raise NonExistentKey(key)
tomlkit.exceptions.NonExistentKey: 'Key "category" does not exist.'
```

**Comment by real-yfprojects** [comment]
I mean why do you differentiate between dev and non dev dependencies? If it is used in `.pre-commit-config.yaml` it should be synced with poetry no matter what.

**Comment by floatingpurr** [comment]
Oh, I'm sorry, I didn't get your question. 

I introduced the `--all` option at the very beginning of the story of this package. It was supposed to be just a kind of a little optimization for going through the collection of `PreCommitRepo`s objects. Indeed, in most cases, `.pre-commit` is used only with dev packages. Usually, your business packages are not part of the `pre-commit` process. But this is not a relevant (or even a good) design, even more so now with this changes introduced in poetry.

You are right, the quickies fix could by simply considering poetry.lock as a whole, without caring anymore about the package type.

**Comment by real-yfprojects** [comment]
:+1: Thanks. I can do a quick review later this week if you like.

**Comment by floatingpurr** [comment]
It’s anything. Sure, thank you!Il giorno 24 mag 2023, alle ore 22:21, yfprojects ***@***.***> ha scritto:﻿
👍 Thanks. I can do a quick review later this week if you like.
